name: Issue Report
title: "[Issue]: "
labels: ["bug"]
assignees:
  - shawnrhoads
description:
  Use this template to open issues regarding design/function of the Neuroimaging Cookbook.
body:
  - type: markdown
    attributes:
      value: Thanks for taking the time to fill out this issue report! Please describe the issue in simple words.
  - type: input
    id: webpage
    attributes:
      label: Webpage
      description: Please paste the URL of the webpage (i.e., links to website or GitHub repository) on which you are experiencing the issue.
      placeholder: ex. https://neuroimaging-cookbook.github.io/template_recipe
    validations:
      required: false
  - type: textarea
    id: description
    attributes:
      label: Description
      description: What is the issue (e.g., typo, bug, inaccurate descriptions, etc.)? Please tell us what you see. What did you expect?
      placeholder: Tell us what you see!
      value: ""
    validations:
      required: true
  - type: checkboxes
    attributes:
      label: Please check any relevant labels
      options:
        - label: content
        - label: documentation
        - label: enhancement
        - label: website
  - type: textarea
    attributes:
      label: Other information
      description:
        Anything else that might be helpful? E.g., related issues, suggestions how to fix, links/references for further context
  - type: dropdown
    id: browsers
    attributes:
      label: If applicable, what browsers are you seeing the problem on?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://neuroimaging-cookbook.github.io/code_of_conduct)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
