name: Recipe Suggestion
title: "[Recipe]: "
labels: ["recipe"]
assignees:
  - shawnrhoads
description:
  Use this template to suggest a new recipe! Please see [this page](https://neuroimaging-cookbook.github.io/template_recipe/) for guidelines on recipes.
body:
  - type: textarea
    id: Description
    attributes:
      description: Please describe the recipe.
      placeholder: Explain briefly how the recipe works. Provide a link to documentation of any third-party software when possible. Try to explain everything briefly, but clearly.
    validations:
      required: true
  - type: checkboxes
    id: Language
    attributes:
      label: What language are you using?
      multiple: true
      options:
        - label: python
        - label: R
        - label: bash
        - label: markdown
        - label: other (specify below)
  - type: input
    id: Modalities
    attributes:
      label: To which modalities does your recipe apply?
      multiple: true
      options:
        - label: fmri
        - label: dmri
        - label: smri
        - label: eeg
        - label: fnirs
        - label: meg
        - label: any
        - label: all
        - label: other (specify below)
    validations:
      required: true
  - type: input
    id: Software
    attributes:
      label: Which software does your recipe require?
      multiple: true
      options:
        - label: afni
        - label: fsl
        - label: spm
        - label: nilearn
        - label: numpy
        - label: pandas
        - label: scipy
        - label: other (specify below)
    validations:
      required: true
  - type: input
    id: Tags
    attributes:
      label: Tags
      description: Please list some other tags that will help users find your recipe.
      placeholder: e.g., mask, nifti, array, roi, connectivity
    validations:
      required: true
  - type: textarea
    id: Ingredients
    attributes:
      label: Ingredients
      description: Please specify the ingredients / software packages / dependencies (and versions) required for this recipe
      placeholder: Use bullet points here.
    validations:
      required: true
  - type: textarea
    id: Recipe
    attributes:
      label: What is your recipe?
      description: Your recipe should be concise. **Your code snippet should be roughly 1-10 lines.** Please do not exceed 100 lines.
      render: shell
    validations:
      required: true
  - type: textarea
    id: Example
    attributes:
      label: What is your example?
      description: Please provide a short example using your recipe.
      render: shell
    validations:
      required: true
  - type: textarea
    id: AdditionalInfo
    attributes:
      label: Anything else?
      description: Is there any other information important for your recipe?
    validations:
      required: false
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://neuroimaging-cookbook.github.io/code_of_conduct)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
